---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: ClusterIP
  selector:
    name: front
  ports:
    -  port: 6666
       targetPort: 6666
---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  type: ClusterIP
  selector:
    name: back
  ports:
    - port: 7777
      targetPort: 7777
