apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - path: /front
        backend:
          serviceName: front
          servicePort: 6666
      - path: /back
        backend:
          serviceName: back
          servicePort: 7777
